"use strict";
exports.__esModule = true;
var vector_1 = require("./vector");
var vector1 = new vector_1.Vector(4, 10);
var vector2 = new vector_1.Vector(4, 20);
vector1.Print();
vector2.Print();
console.log(vector1.Add(vector2));
console.log(vector1.Subs(vector2));
console.log(vector1.Mult(vector2));
console.log(vector1.multNumber(2));
