"use strict";
exports.__esModule = true;
var Mobile_1 = require("./Mobile");
var Nokia = new Mobile_1.Mobile("Nokia", "3210", "Orange", 32, "Gris", false, 0, 50);
var Iphone = new Mobile_1.Mobile("Iphone", "3G", "Movistar", 64, "Azul", false, 1, 100);
var Samsung = new Mobile_1.Mobile("Samsung", "Calaxy 10", "Vodafone", 128, "Negro", true, 2, 120);
console.log(Nokia.toString());
console.log(Iphone.toString());
console.log(Samsung.toString());
Nokia.setis5G(true);
Nokia.setcameraNumber(4);
console.log(Nokia.toString());
console.log(Iphone.toString());
console.log(Samsung.toString());
console.log(Nokia.getprice());
